---
- include_vars: "{{ item }}"
  with_items: 
    - vars.yml
    
- name: Add a new Fullmember user to Slack
  uri:
    url: https://{{slackteamname}}.slack.com/api/users.admin.invite
    method: POST
    return_content: yes  
    HEADER_Content-Type: "application/x-www-form-urlencoded"
    body: "email={{privatemail}}&token={{token}}&set_active=true"

